### ISSUE TITLE
Increment in one transaction

### ISSUE THREAD

**Issue by fabianfiorotto** [zdivozzo/increment-me#5]
so it can be undone with only one ctrl-z if you make a mistake. The code should look like this

```coffeescript
 convert: ->

    editor = atom.workspace.getActiveTextEditor()
    selections = editor.getSelectionsOrderedByBufferPosition()
    seedNumber = 1

    editor.transact 0, ->
      selections.forEach (selection, index) ->
         #..............etc
```

**Comment by Scimonster** [comment]
@fabianfiorotto How about you make a pull request?

**Comment by fabianfiorotto** [comment]
I could do it. But I think that this package is not maintained anymore :disappointed:

**Comment by Scimonster** [comment]
If nothing happens with the PR, it's always possible to release your own fork.

**Comment by fabianfiorotto** [comment]
It's done.
